# Generated by Django 3.2.6 on 2021-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imag', models.ImageField(upload_to='picture')),
                ('category', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
