# Generated by Django 3.2.6 on 2021-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.IntegerField(default='05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='month',
            field=models.TextField(default='May', max_length=10),
            preserve_default=False,
        ),
    ]
